"""Write nginx vhost + reload (Part E).

**DNS (wildcard):** Production expects a wildcard A/AAAA record::

    *.thiramai.co.in  →  <your VPS or load balancer IP>

Without this, per-tenant subdomains like ``https://acme-3.thiramai.co.in`` will not resolve.

**Deploy safety:** File writes only under ``THIRAMAI_NGINX_CONF_DIR`` (default ``./nginx-generated`` in repo)
unless ``THIRAMAI_WEB_DEPLOY_USE_SYSTEM_PATHS=1``, which targets
``/etc/nginx/sites-available`` and ``sites-enabled`` (requires root).

``THIRAMAI_WEB_DEPLOY_ENABLED=1`` is required to attempt ``nginx -s reload``.
"""

from __future__ import annotations

import logging
import os
import platform
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from services.website_builder_service import _public_domain, _sites_root

_log = logging.getLogger("thiramai.website_deploy")


def _nginx_conf_dir() -> Path:
    if (os.getenv("THIRAMAI_WEB_DEPLOY_USE_SYSTEM_PATHS") or "").strip() == "1":
        return Path("/etc/nginx/sites-available")
    raw = (os.getenv("THIRAMAI_NGINX_CONF_DIR") or "").strip()
    if raw:
        return Path(raw).expanduser().resolve()
    return (Path.cwd() / "nginx-generated").resolve()


def _nginx_enabled_dir() -> Path:
    if (os.getenv("THIRAMAI_WEB_DEPLOY_USE_SYSTEM_PATHS") or "").strip() == "1":
        return Path("/etc/nginx/sites-enabled")
    return _nginx_conf_dir() / "enabled"


def _validate_slug(slug: str) -> bool:
    return bool(re.fullmatch(r"[a-z0-9][a-z0-9-]{1,62}[a-z0-9]", slug))


def deploy_site_sync(business_slug: str, *, site_root: Path | None = None) -> dict[str, Any]:
    """
    Create nginx ``server`` block pointing at static root and optionally reload nginx.

    On Windows, or when ``THIRAMAI_WEB_DEPLOY_ENABLED`` is not ``1``, writes config only
    (no system reload).
    """
    slug = (business_slug or "").strip().lower()
    if not _validate_slug(slug):
        return {"ok": False, "error": "invalid slug"}

    root = (site_root or _sites_root()).resolve()
    docroot = (root / slug).resolve()
    if not str(docroot).startswith(str(root)) or not docroot.is_dir():
        return {"ok": False, "error": "site directory missing — run build first"}

    domain = _public_domain()
    server_name = f"{slug}.{domain}"
    conf_dir = _nginx_conf_dir()
    enabled_root = _nginx_enabled_dir()
    try:
        conf_dir.mkdir(parents=True, exist_ok=True)
        enabled_root.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        return {"ok": False, "error": f"cannot create nginx dirs: {exc}"}

    conf_name = f"thiramai-{slug}.conf"
    conf_path = conf_dir / conf_name
    body = f"""# Auto-generated by THIRAMAI Part E — do not hand-edit without review
server {{
    listen 80;
    listen [::]:80;
    server_name {server_name};
    root {docroot.as_posix()};
    index index.html;
    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""
    try:
        conf_path.write_text(body, encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"write nginx conf failed: {exc}"}

    enabled_link = enabled_root / conf_name
    try:
        if enabled_link.exists() or enabled_link.is_symlink():
            enabled_link.unlink()
        try:
            enabled_link.symlink_to(conf_path)
        except OSError:
            shutil.copy2(conf_path, enabled_link)
    except OSError as exc:
        return {"ok": False, "error": f"enable site failed: {exc}", "conf_path": str(conf_path)}

    deploy_enabled = (os.getenv("THIRAMAI_WEB_DEPLOY_ENABLED") or "").strip() == "1"
    if not deploy_enabled or platform.system().lower().startswith("win"):
        return {
            "ok": True,
            "skipped_reload": True,
            "message": "Config written. Set THIRAMAI_WEB_DEPLOY_ENABLED=1 on Linux with nginx for reload, "
            "or copy conf to your server.",
            "conf_path": str(conf_path),
            "enabled_path": str(enabled_link),
            "server_name": server_name,
            "docroot": str(docroot),
            "wildcard_dns_note": f"Ensure *.{_public_domain()} resolves to this host.",
        }

    try:
        test = subprocess.run(
            ["nginx", "-t"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if test.returncode != 0:
            return {
                "ok": False,
                "error": (test.stderr or test.stdout or "nginx -t failed").strip(),
                "conf_path": str(conf_path),
            }
        reload = subprocess.run(
            ["nginx", "-s", "reload"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if reload.returncode != 0:
            return {
                "ok": False,
                "error": (reload.stderr or reload.stdout or "reload failed").strip(),
                "conf_path": str(conf_path),
            }
    except FileNotFoundError:
        return {"ok": False, "error": "nginx binary not found", "conf_path": str(conf_path)}
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "nginx command timed out", "conf_path": str(conf_path)}

    return {
        "ok": True,
        "reloaded": True,
        "conf_path": str(conf_path),
        "enabled_path": str(enabled_link),
        "server_name": server_name,
        "public_url": f"https://{server_name}/",
        "docroot": str(docroot),
    }
