#!/usr/bin/env bash
# =============================================================================
# THIRAMAI — one-shot VPS production bootstrap (no manual .env editing)
# =============================================================================
# Run ON THE SERVER as root, from the repo root (e.g. /root/thiramai-app):
#
#   sudo bash scripts/provision_vps_auto.sh
#
# What it does:
#   - Writes /root/thiramai-app/.env.production (or $APP_DIR) with safe DATABASE_URL
#     (password @ is URL-encoded — required for MyDB@123 style passwords)
#   - Generates SECRET_KEY (openssl rand -hex 32)
#   - Installs docker.io + Docker Compose v2 plugin if missing
#   - Starts db + redis, runs alembic upgrade head, brings full stack up
#   - Verifies docker ps + curl /health/ready (NOT /docs — OpenAPI is disabled in production)
#
# Override install directory:
#   APP_DIR=/opt/thiramai sudo -E bash scripts/provision_vps_auto.sh
# =============================================================================
set -euo pipefail

APP_DIR="${APP_DIR:-/root/thiramai-app}"
COMPOSE_FILE="docker-compose.production.yml"
ENV_FILE=".env.production"

# --- Tunables (match requested production profile) ---
POSTGRES_USER="${POSTGRES_USER:-thiramai}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-MyDB@123}"
POSTGRES_DB="${POSTGRES_DB:-thiramai}"
WEB_PORT="${WEB_PORT:-8000}"
PUBLIC_IP="${PUBLIC_IP:-139.59.24.80}"
CORS_EXTRA="${CORS_EXTRA:-http://${PUBLIC_IP},http://${PUBLIC_IP}:5173}"

cd "$APP_DIR" || {
  echo "ERROR: APP_DIR=$APP_DIR does not exist. Clone the repo there first:"
  echo "  git clone https://github.com/murugamodern-coder/THIRAMAI_GENESIS.git $APP_DIR"
  exit 1
}

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "ERROR: $COMPOSE_FILE not found in $APP_DIR"
  exit 1
fi

# URL-encode password for SQLAlchemy URL (@ breaks user:pass@host)
if command -v python3 &>/dev/null; then
  ENC_PASS="$(python3 -c "import urllib.parse; print(urllib.parse.quote('''${POSTGRES_PASSWORD}''', safe=''))")"
else
  echo "ERROR: python3 required for password URL encoding"
  exit 1
fi

SECRET_KEY="${SECRET_KEY_OVERRIDE:-}"
if [[ -z "$SECRET_KEY" ]]; then
  SECRET_KEY="$(openssl rand -hex 32)"
fi

DATABASE_URL="postgresql+psycopg2://${POSTGRES_USER}:${ENC_PASS}@db:5432/${POSTGRES_DB}"

umask 077
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/provision_vps_auto.sh — do not commit
ENV=production
THIRAMAI_ENV=production

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
WEB_PORT=${WEB_PORT}

DATABASE_URL=${DATABASE_URL}

SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256
JWT_EXPIRE_MINUTES=1440

GROQ_API_KEY=dummy
TAVILY_API_KEY=dummy

THIRAMAI_CORS_ORIGINS=${CORS_EXTRA}
THIRAMAI_SAFE_ERRORS=1
THIRAMAI_RL_TRUST_X_FORWARDED_FOR=1
THIRAMAI_PROXY_TRUSTED_HOSTS=*
THIRAMAI_LOG_JSON=1

THIRAMAI_AUTH_DISABLED=0

THIRAMAI_ENABLE_ALERT_SCHEDULER=1
THIRAMAI_ALERT_INTERVAL_MINUTES=15
THIRAMAI_ALERT_LOW_STOCK_THRESHOLD=10

REDIS_URL=redis://redis:6379/0

THIRAMAI_JOB_QUEUE=db
THIRAMAI_WORKER_POLL_SEC=2

SOVEREIGN_BYPASS_HITL=0

THIRAMAI_RL_AUTH_PER_MINUTE=20
THIRAMAI_RL_CHAT_PER_MINUTE=40
THIRAMAI_RL_CHAT_QUERY_PER_USER_PER_MINUTE=30
EOF

chmod 600 "$ENV_FILE"

echo "=== Validate .env.production ==="
if ! grep -q "^DATABASE_URL=postgresql+psycopg2://" "$ENV_FILE"; then
  echo "ERROR: DATABASE_URL missing or invalid"
  exit 1
fi
if [[ "$POSTGRES_PASSWORD" == *"@"* ]]; then
  if ! grep '^DATABASE_URL=' "$ENV_FILE" | grep -q '%40'; then
    echo "ERROR: password contains @ but DATABASE_URL must URL-encode it as %40"
    exit 1
  fi
fi
echo "OK: $ENV_FILE written ($(wc -l < "$ENV_FILE") lines)"

# --- Docker ---
if ! command -v docker &>/dev/null; then
  echo "=== Installing Docker ==="
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y docker.io
  systemctl enable --now docker || true
fi

if ! docker compose version &>/dev/null 2>&1; then
  echo "=== Installing Docker Compose plugin ==="
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y docker-compose-v2 2>/dev/null || apt-get install -y docker-compose-plugin 2>/dev/null || {
    echo "ERROR: Install docker compose v2: apt install docker-compose-v2"
    exit 1
  }
fi

DC=(docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE")

echo "=== Build & start database + redis ==="
"${DC[@]}" up -d --build db redis

echo "=== Wait for Postgres healthy ==="
for i in $(seq 1 60); do
  if "${DC[@]}" exec -T db pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" &>/dev/null; then
    echo "Postgres is ready"
    break
  fi
  sleep 2
  if [[ "$i" -eq 60 ]]; then
    echo "ERROR: Postgres did not become ready"
    "${DC[@]}" logs db --tail 80
    exit 1
  fi
done

echo "=== Alembic migrate ==="
"${DC[@]}" run --rm --no-deps --entrypoint "" web alembic upgrade head

echo "=== Start full stack ==="
"${DC[@]}" up -d --build

echo "=== docker ps ==="
docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'

echo "=== Health check (production: /docs is disabled; use /health/ready) ==="
sleep 5
if curl -fsS "http://127.0.0.1:${WEB_PORT}/health/ready" -o /tmp/thiramai_health.json; then
  echo "OK: GET /health/ready -> 200"
  head -c 300 /tmp/thiramai_health.json || true
  echo
else
  echo "WARN: /health/ready failed — recent web logs:"
  "${DC[@]}" logs web --tail 100 || true
  exit 1
fi

echo
echo "=== SUCCESS ==="
echo "API (loopback): http://127.0.0.1:${WEB_PORT}/"
echo "Health:         curl -s http://127.0.0.1:${WEB_PORT}/health/ready"
echo "OpenAPI UI is OFF in production; use curl or a client against the API."
